<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Simple template</title>
    <style>
        body {
            background: #888;
            color: #fff;
        }
    </style>
</head>
<body>
    <h3>Hy!</h3>
    <p>This is simple template!</p>
    <h4>Nav links</h4>
<?php
    /**
     * Grab child block
     */
    echo $this->getChildHtml('top.links');
?>
</body>
</html>